const weatherCode = {
    0: "http://openweathermap.org/img/wn/01d@2x.png",
    1: "http://openweathermap.org/img/wn/01d@2x.png",
    2: "http://openweathermap.org/img/wn/02d@2x.png",
    3: "http://openweathermap.org/img/wn/03d@2x.png",
    45: "http://openweathermap.org/img/wn/50d@2x.png",
    48: "http://openweathermap.org/img/wn/50d@2x.png",
    51: "http://openweathermap.org/img/wn/09d@2x.png",
    53: "http://openweathermap.org/img/wn/09d@2x.png",
    55: "http://openweathermap.org/img/wn/09d@2x.png",
    56: "http://openweathermap.org/img/wn/09d@2x.png",
    57: "http://openweathermap.org/img/wn/09d@2x.png",
    61: "http://openweathermap.org/img/wn/10d@2x.png",
    63: "http://openweathermap.org/img/wn/10d@2x.png",
    65: "http://openweathermap.org/img/wn/10d@2x.png",
    66: "http://openweathermap.org/img/wn/10d@2x.png",
    67: "http://openweathermap.org/img/wn/10d@2x.png",
    71: "http://openweathermap.org/img/wn/13d@2x.png",
    73: "http://openweathermap.org/img/wn/13d@2x.png",
    75: "http://openweathermap.org/img/wn/13d@2x.png",
    77: "http://openweathermap.org/img/wn/13d@2x.png",
    80: "http://openweathermap.org/img/wn/09d@2x.png",
    81: "http://openweathermap.org/img/wn/09d@2x.png",
    82: "http://openweathermap.org/img/wn/09d@2x.png",
    85: "http://openweathermap.org/img/wn/13d@2x.png",
    86: "http://openweathermap.org/img/wn/13d@2x.png",
    95: "http://openweathermap.org/img/wn/11d@2x.png",
    96: "http://openweathermap.org/img/wn/11d@2x.png",
    99: "http://openweathermap.org/img/wn/11d@2x.png",
  };
  
  export default weatherCode;